# rbac-code-execution.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adk-code-executor
  namespace: agent-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: code-executor-role
  namespace: agent-code-execution
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "watch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-executor-binding
  namespace: agent-code-execution
subjects:
  - kind: ServiceAccount
    name: adk-code-executor
    namespace: agent-ns
roleRef:
  kind: Role
  name: code-executor-role
  apiGroup: rbac.authorization.k8s.io
